# Generated by Django 5.1.1 on 2024-09-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_remove_mediadetail_user_quote_mediadetail_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
